//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DashboardEntities : DbContext
    {
        public DashboardEntities()
            : base("name=DashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<thousedesignation> thousedesignations { get; set; }
        public DbSet<thouseelection> thouseelections { get; set; }
        public DbSet<thousenomination> thousenominations { get; set; }
        public DbSet<thous> thouses { get; set; }
        public DbSet<tsenatedesignation> tsenatedesignations { get; set; }
        public DbSet<tsenateelection> tsenateelections { get; set; }
        public DbSet<tsenatenomination> tsenatenominations { get; set; }
        public DbSet<tstudent> tstudents { get; set; }
        public DbSet<tvotedstudent> tvotedstudents { get; set; }
    }
}
