//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tclasssection
    {
        public int Csc_Id { get; set; }
        public Nullable<int> Csc_ClassId { get; set; }
        public Nullable<int> Csc_SectionId { get; set; }
        public string Csc_DisplayName { get; set; }
        public Nullable<bool> Csc_IsDeleted { get; set; }
        public Nullable<System.DateTime> Csc_DeletedDate { get; set; }
        public Nullable<int> Csc_DeletedBy { get; set; }
        public Nullable<System.DateTime> Csc_LastUpdatedDate { get; set; }
        public Nullable<int> Csc_LastUpdatedBy { get; set; }
    
        public virtual tclass tclass { get; set; }
        public virtual tsection tsection { get; set; }
    }
}
