//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsenateelection
    {
        public tsenateelection()
        {
            this.tsenatenominations = new HashSet<tsenatenomination>();
        }
    
        public int Sel_ElectionId { get; set; }
        public System.DateTime Sel_StartDate { get; set; }
        public System.DateTime Sel_EndDate { get; set; }
        public string Sel_Description { get; set; }
    
        public virtual ICollection<tsenatenomination> tsenatenominations { get; set; }
    }
}
