//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsenatedesignation
    {
        public tsenatedesignation()
        {
            this.tsenatenominations = new HashSet<tsenatenomination>();
        }
    
        public int Sen_Id { get; set; }
        public string Sen_Name { get; set; }
        public string Sen_Description { get; set; }
        public string Sen_DesCode { get; set; }
        public Nullable<int> Sen_Gender { get; set; }
        public Nullable<bool> Sen_IsDeleted { get; set; }
        public Nullable<System.DateTime> Sen_DeletedDate { get; set; }
        public Nullable<int> Sen_DeletedBy { get; set; }
        public Nullable<System.DateTime> Sen_LastUpdatedDate { get; set; }
        public Nullable<int> Sen_LastUpdatedBy { get; set; }
    
        public virtual ICollection<tsenatenomination> tsenatenominations { get; set; }
    }
}
